//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_ticaret.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("E_ticaret.Resources.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama.
        /// </summary>
        public static string aciklama {
            get {
                return ResourceManager.GetString("aciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Admin Ekle.
        /// </summary>
        public static string admin {
            get {
                return ResourceManager.GetString("admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Adı.
        /// </summary>
        public static string adminad {
            get {
                return ResourceManager.GetString("adminad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Soyadı.
        /// </summary>
        public static string adminsoyad {
            get {
                return ResourceManager.GetString("adminsoyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADRESLER.
        /// </summary>
        public static string Adresler {
            get {
                return ResourceManager.GetString("Adresler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARA.
        /// </summary>
        public static string Ara {
            get {
                return ResourceManager.GetString("Ara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlık.
        /// </summary>
        public static string baslik {
            get {
                return ResourceManager.GetString("baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beni Hatırla.
        /// </summary>
        public static string Benihatirla {
            get {
                return ResourceManager.GetString("Benihatirla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BİLGİLENDİRME.
        /// </summary>
        public static string Bilgilendirme {
            get {
                return ResourceManager.GetString("Bilgilendirme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BİLGİLERİNİZ.
        /// </summary>
        public static string Bilgileriniz {
            get {
                return ResourceManager.GetString("Bilgileriniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sadece gerekli alanları göster.
        /// </summary>
        public static string Cgerekli {
            get {
                return ResourceManager.GetString("Cgerekli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış.
        /// </summary>
        public static string cikis {
            get {
                return ResourceManager.GetString("cikis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinsiyet.
        /// </summary>
        public static string cinsiyet {
            get {
                return ResourceManager.GetString("cinsiyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstek Veya Şikayet Bildir.
        /// </summary>
        public static string Cistek {
            get {
                return ResourceManager.GetString("Cistek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesajınız başarıyla gönderilmiştir..
        /// </summary>
        public static string Cmesaj {
            get {
                return ResourceManager.GetString("Cmesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaylar.
        /// </summary>
        public static string detaylar {
            get {
                return ResourceManager.GetString("detaylar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Seç.
        /// </summary>
        public static string dosyasec {
            get {
                return ResourceManager.GetString("dosyasec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Seçilmedi.
        /// </summary>
        public static string dosyasecilemedi {
            get {
                return ResourceManager.GetString("dosyasecilemedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUYURULAR.
        /// </summary>
        public static string Duyurular {
            get {
                return ResourceManager.GetString("Duyurular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düzenle.
        /// </summary>
        public static string duzenle {
            get {
                return ResourceManager.GetString("duzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        public static string Ekle {
            get {
                return ResourceManager.GetString("Ekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En Çok Satanlar.
        /// </summary>
        public static string Encoksatan {
            get {
                return ResourceManager.GetString("Encoksatan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta adresiniz.
        /// </summary>
        public static string Eposta {
            get {
                return ResourceManager.GetString("Eposta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirmaBilgisi.
        /// </summary>
        public static string firmahakkinda {
            get {
                return ResourceManager.GetString("firmahakkinda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fotoğraf.
        /// </summary>
        public static string foto {
            get {
                return ResourceManager.GetString("foto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Giriş.
        /// </summary>
        public static string Giris {
            get {
                return ResourceManager.GetString("Giris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönder.
        /// </summary>
        public static string gonder {
            get {
                return ResourceManager.GetString("gonder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Günün Ürünleri.
        /// </summary>
        public static string gununurunleri {
            get {
                return ResourceManager.GetString("gununurunleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAKKIMIZDA.
        /// </summary>
        public static string Hakkimizda {
            get {
                return ResourceManager.GetString("Hakkimizda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda.
        /// </summary>
        public static string Hakkimizdaa {
            get {
                return ResourceManager.GetString("Hakkimizdaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HESABINIZ.
        /// </summary>
        public static string Hesabiniz {
            get {
                return ResourceManager.GetString("Hesabiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoşgeldiniz !.
        /// </summary>
        public static string Hosgeldin {
            get {
                return ResourceManager.GetString("Hosgeldin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İLETİŞİM.
        /// </summary>
        public static string Iletisim {
            get {
                return ResourceManager.GetString("Iletisim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        public static string iletisimm {
            get {
                return ResourceManager.GetString("iletisimm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlangıç Tarihi.
        /// </summary>
        public static string ilktarih {
            get {
                return ResourceManager.GetString("ilktarih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İNCELE.
        /// </summary>
        public static string incele {
            get {
                return ResourceManager.GetString("incele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İndirimdeki Ürünlerimiz.
        /// </summary>
        public static string indirimdekiurun {
            get {
                return ResourceManager.GetString("indirimdekiurun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İNDİRİMLERİMİZ.
        /// </summary>
        public static string indirimleriniz {
            get {
                return ResourceManager.GetString("indirimleriniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İndirim Oranı.
        /// </summary>
        public static string indirimorani {
            get {
                return ResourceManager.GetString("indirimorani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem.
        /// </summary>
        public static string islem {
            get {
                return ResourceManager.GetString("islem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kampanya Adı.
        /// </summary>
        public static string kampanyaadi {
            get {
                return ResourceManager.GetString("kampanyaadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kampanya Adına Göre Arama :.
        /// </summary>
        public static string kampanyaarama {
            get {
                return ResourceManager.GetString("kampanyaarama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kampanya Hakkında.
        /// </summary>
        public static string kampanyahakkinda {
            get {
                return ResourceManager.GetString("kampanyahakkinda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kampanyalı Ürünlerimiz.
        /// </summary>
        public static string kampanyaliurun {
            get {
                return ResourceManager.GetString("kampanyaliurun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAMPANYALAR.
        /// </summary>
        public static string KampanyaUrun {
            get {
                return ResourceManager.GetString("KampanyaUrun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kampanya Yönetimi.
        /// </summary>
        public static string kampanyayonetim {
            get {
                return ResourceManager.GetString("kampanyayonetim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAPAT.
        /// </summary>
        public static string Kapat {
            get {
                return ResourceManager.GetString("Kapat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kargo.
        /// </summary>
        public static string kargo {
            get {
                return ResourceManager.GetString("kargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KargoAdı.
        /// </summary>
        public static string kargoad {
            get {
                return ResourceManager.GetString("kargoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KargoArama.
        /// </summary>
        public static string kargoarama {
            get {
                return ResourceManager.GetString("kargoarama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kargo Ekle.
        /// </summary>
        public static string kargoekle {
            get {
                return ResourceManager.GetString("kargoekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kargolar.
        /// </summary>
        public static string kargolar {
            get {
                return ResourceManager.GetString("kargolar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kargo Yonetimi.
        /// </summary>
        public static string kargoyonetim {
            get {
                return ResourceManager.GetString("kargoyonetim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori.
        /// </summary>
        public static string kategori {
            get {
                return ResourceManager.GetString("kategori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Adına Göre Arama :.
        /// </summary>
        public static string kategoriarama {
            get {
                return ResourceManager.GetString("kategoriarama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Seç.
        /// </summary>
        public static string kategorisec {
            get {
                return ResourceManager.GetString("kategorisec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Yönetimi.
        /// </summary>
        public static string kategoriyonetim {
            get {
                return ResourceManager.GetString("kategoriyonetim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        public static string kaydet {
            get {
                return ResourceManager.GetString("kaydet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Tarihi.
        /// </summary>
        public static string Kayittarihi {
            get {
                return ResourceManager.GetString("Kayittarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KOŞULLAR.
        /// </summary>
        public static string Kosullar {
            get {
                return ResourceManager.GetString("Kosullar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marka.
        /// </summary>
        public static string marka {
            get {
                return ResourceManager.GetString("marka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marka Adı.
        /// </summary>
        public static string markaad {
            get {
                return ResourceManager.GetString("markaad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marka Adına Göre Arama :.
        /// </summary>
        public static string markaarama {
            get {
                return ResourceManager.GetString("markaarama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marka Ekle.
        /// </summary>
        public static string markaekle {
            get {
                return ResourceManager.GetString("markaekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marka Hakkında.
        /// </summary>
        public static string markahakkinda {
            get {
                return ResourceManager.GetString("markahakkinda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markalar.
        /// </summary>
        public static string markalar {
            get {
                return ResourceManager.GetString("markalar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marka Seç.
        /// </summary>
        public static string markasec {
            get {
                return ResourceManager.GetString("markasec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marka Yönetimi.
        /// </summary>
        public static string markayonetim {
            get {
                return ResourceManager.GetString("markayonetim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neredeyiz?.
        /// </summary>
        public static string nerede {
            get {
                return ResourceManager.GetString("nerede", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödeme Şekilleri.
        /// </summary>
        public static string Odeme {
            get {
                return ResourceManager.GetString("Odeme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÖZEL TEKLİFLERİMİZ.
        /// </summary>
        public static string ozelteklif {
            get {
                return ResourceManager.GetString("ozelteklif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepetiniz.
        /// </summary>
        public static string Sepet {
            get {
                return ResourceManager.GetString("Sepet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        public static string sfr {
            get {
                return ResourceManager.GetString("sfr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ŞİFRE.
        /// </summary>
        public static string sifre {
            get {
                return ResourceManager.GetString("sifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string sil {
            get {
                return ResourceManager.GetString("sil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Adına Göre Arama :.
        /// </summary>
        public static string sliderarama {
            get {
                return ResourceManager.GetString("sliderarama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Yönetimi.
        /// </summary>
        public static string slideryonetim {
            get {
                return ResourceManager.GetString("slideryonetim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonraki.
        /// </summary>
        public static string sonraki {
            get {
                return ResourceManager.GetString("sonraki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitiş Tarihi.
        /// </summary>
        public static string sontarih {
            get {
                return ResourceManager.GetString("sontarih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Görüntülenen Ürünler.
        /// </summary>
        public static string SonUrun {
            get {
                return ResourceManager.GetString("SonUrun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOSYAL MEDYADAN BİZİ TAKİP EDİN.
        /// </summary>
        public static string Sosyal {
            get {
                return ResourceManager.GetString("Sosyal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSS.
        /// </summary>
        public static string SSS {
            get {
                return ResourceManager.GetString("SSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEKLİFLERİMİZ.
        /// </summary>
        public static string Teklif {
            get {
                return ResourceManager.GetString("Teklif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string telefon {
            get {
                return ResourceManager.GetString("telefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TÜMÜ.
        /// </summary>
        public static string Tum {
            get {
                return ResourceManager.GetString("Tum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Kampanyalar.
        /// </summary>
        public static string Tumkampanya {
            get {
                return ResourceManager.GetString("Tumkampanya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TÜM SİPARİŞLERİNİZ.
        /// </summary>
        public static string Tumsiparis {
            get {
                return ResourceManager.GetString("Tumsiparis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÜRETİCİLERİMİZ.
        /// </summary>
        public static string Ureticiler {
            get {
                return ResourceManager.GetString("Ureticiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Adı.
        /// </summary>
        public static string urunadi {
            get {
                return ResourceManager.GetString("urunadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Adı Giriniz.
        /// </summary>
        public static string urunadigir {
            get {
                return ResourceManager.GetString("urunadigir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Adına Göre Arama :.
        /// </summary>
        public static string urunarama {
            get {
                return ResourceManager.GetString("urunarama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Ekleme Sayfası.
        /// </summary>
        public static string uruneklemesayfasi {
            get {
                return ResourceManager.GetString("uruneklemesayfasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Fiyat.
        /// </summary>
        public static string urunfiyat {
            get {
                return ResourceManager.GetString("urunfiyat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünü Kaydet.
        /// </summary>
        public static string urunkaydet {
            get {
                return ResourceManager.GetString("urunkaydet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÜRÜNLERİMİZ.
        /// </summary>
        public static string Urunler {
            get {
                return ResourceManager.GetString("Urunler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünleri Listele.
        /// </summary>
        public static string urunlerilistele {
            get {
                return ResourceManager.GetString("urunlerilistele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Resim.
        /// </summary>
        public static string urunresim {
            get {
                return ResourceManager.GetString("urunresim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Yönetimi.
        /// </summary>
        public static string urunyonetim {
            get {
                return ResourceManager.GetString("urunyonetim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Adı.
        /// </summary>
        public static string uyead {
            get {
                return ResourceManager.GetString("uyead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Adına Göre Arama :.
        /// </summary>
        public static string uyearama {
            get {
                return ResourceManager.GetString("uyearama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üyeler.
        /// </summary>
        public static string uyeler {
            get {
                return ResourceManager.GetString("uyeler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÜYELİK İŞLEMLERİ.
        /// </summary>
        public static string Uyelikislem {
            get {
                return ResourceManager.GetString("Uyelikislem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üyelik Yönetimi.
        /// </summary>
        public static string uyelikislemleri {
            get {
                return ResourceManager.GetString("uyelikislemleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Ol.
        /// </summary>
        public static string UyeOl {
            get {
                return ResourceManager.GetString("UyeOl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAYIT OLMA.
        /// </summary>
        public static string uyeoll {
            get {
                return ResourceManager.GetString("uyeoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Soyadı.
        /// </summary>
        public static string uyesoyad {
            get {
                return ResourceManager.GetString("uyesoyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Admin.
        /// </summary>
        public static string yeniadmin {
            get {
                return ResourceManager.GetString("yeniadmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Kampanya.
        /// </summary>
        public static string yenikampanya {
            get {
                return ResourceManager.GetString("yenikampanya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ss.
        /// </summary>
        public static string yenikargo {
            get {
                return ResourceManager.GetString("yenikargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Kategori.
        /// </summary>
        public static string yenikategori {
            get {
                return ResourceManager.GetString("yenikategori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Marka.
        /// </summary>
        public static string yenimarka {
            get {
                return ResourceManager.GetString("yenimarka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Slide.
        /// </summary>
        public static string yenislide {
            get {
                return ResourceManager.GetString("yenislide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Ürün.
        /// </summary>
        public static string yeniurun {
            get {
                return ResourceManager.GetString("yeniurun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En Yeni Urunlerimiz.
        /// </summary>
        public static string yeniurunler {
            get {
                return ResourceManager.GetString("yeniurunler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Üye.
        /// </summary>
        public static string yeniuye {
            get {
                return ResourceManager.GetString("yeniuye", resourceCulture);
            }
        }
    }
}
