//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_ticaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banka
    {
        public Banka()
        {
            this.Taksitler = new HashSet<Taksitler>();
        }
    
        public int bankaId { get; set; }
        public string bankaadi { get; set; }
        public byte[] logo { get; set; }
    
        public virtual ICollection<Taksitler> Taksitler { get; set; }
    }
}
