//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_ticaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fiyat
    {
        public int fiyatId { get; set; }
        public Nullable<decimal> alisfiyati { get; set; }
        public Nullable<int> kdv { get; set; }
        public Nullable<int> karorani { get; set; }
        public Nullable<int> kampanyaId { get; set; }
        public Nullable<int> urunId { get; set; }
    
        public virtual Urun Urun { get; set; }
    }
}
