//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_ticaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kampanya
    {
        public Kampanya()
        {
            this.Urun1 = new HashSet<Urun>();
        }
    
        public int kampanyaId { get; set; }
        public Nullable<int> urunId { get; set; }
        public Nullable<int> indirimorani { get; set; }
        public Nullable<System.DateTime> baslangictarihi { get; set; }
        public Nullable<System.DateTime> bitistarihi { get; set; }
        public string kampanyabasligi { get; set; }
        public string kampanyaaciklamasi { get; set; }
        public byte[] kampanyagorseli { get; set; }
    
        public virtual Urun Urun { get; set; }
        public virtual ICollection<Urun> Urun1 { get; set; }
    }
}
