//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_ticaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kargo
    {
        public Kargo()
        {
            this.Siparis = new HashSet<Siparis>();
        }
    
        public int kargoId { get; set; }
        public string firmaadi { get; set; }
        public string firmaaciklamasi { get; set; }
    
        public virtual ICollection<Siparis> Siparis { get; set; }
    }
}
