//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_ticaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategori
    {
        public Kategori()
        {
            this.Urun = new HashSet<Urun>();
        }
    
        public int kategoriId { get; set; }
        public string kategoriadi { get; set; }
        public Nullable<int> anakategoriId { get; set; }
    
        public virtual ICollection<Urun> Urun { get; set; }
    }
}
