//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_ticaret.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Marka
    {
        public Marka()
        {
            this.Urun = new HashSet<Urun>();
        }
    
        public int markaId { get; set; }
        [Required(ErrorMessage = "Lütfen bir ad giriniz")]
        public string markaadi { get; set; }
        public string aciklama { get; set; }
        public byte[] firmaresmi { get; set; }
    
        public virtual ICollection<Urun> Urun { get; set; }
    }
}
