//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_ticaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis
    {
        public Siparis()
        {
            this.Fatura = new HashSet<Fatura>();
            this.Urun1 = new HashSet<Urun>();
        }
    
        public int siparisId { get; set; }
        public Nullable<int> urunId { get; set; }
        public Nullable<int> sepetId { get; set; }
        public Nullable<System.DateTime> siparistarihi { get; set; }
        public Nullable<int> kargoId { get; set; }
        public Nullable<int> taksitId { get; set; }
        public Nullable<int> odemesecenekId { get; set; }
        public Nullable<int> kargono { get; set; }
    
        public virtual ICollection<Fatura> Fatura { get; set; }
        public virtual Kargo Kargo { get; set; }
        public virtual OdemeSecenek OdemeSecenek { get; set; }
        public virtual Sepet Sepet { get; set; }
        public virtual Taksitler Taksitler { get; set; }
        public virtual Urun Urun { get; set; }
        public virtual ICollection<Urun> Urun1 { get; set; }
    }
}
