//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_ticaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slider
    {
        public int sliderId { get; set; }
        public byte[] sliderfoto { get; set; }
        public string slidertext { get; set; }
        public Nullable<System.DateTime> baslangictarihi { get; set; }
        public Nullable<System.DateTime> bitistarihi { get; set; }
    }
}
