//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_ticaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taksitler
    {
        public Taksitler()
        {
            this.Siparis = new HashSet<Siparis>();
        }
    
        public int taksitId { get; set; }
        public Nullable<int> bankaId { get; set; }
        public Nullable<int> urunId { get; set; }
        public Nullable<int> taksittabloId { get; set; }
    
        public virtual Banka Banka { get; set; }
        public virtual ICollection<Siparis> Siparis { get; set; }
        public virtual TaksitTablo TaksitTablo { get; set; }
        public virtual Urun Urun { get; set; }
    }
}
