//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_ticaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UyeGorus
    {
        public int gorusId { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string gorus { get; set; }
        public Nullable<System.DateTime> gorustarihi { get; set; }
    }
}
