//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_ticaret.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Uyeler
    {
        public Uyeler()
        {
            this.Fatura = new HashSet<Fatura>();
            this.Sepet = new HashSet<Sepet>();
        }
    
        public int uyeId { get; set; }
        public Nullable<int> rolId { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string telefon { get; set; }
        public string tc { get; set; }
        public string parola { get; set; }
        [Required( ErrorMessage="lütfen mail giriniz")]
        [RegularExpression(".+\\@.+\\..+",ErrorMessage="lütfen geçerli bir mail giriniz")]
        public string email { get; set; }
        public string guvenliksorusu { get; set; }
        public string guvenliksorusucevap { get; set; }
        public Nullable<System.DateTime> kayittarihi { get; set; }
        public string adres { get; set; }
        public string cinsiyet { get; set; }
    
        public virtual ICollection<Fatura> Fatura { get; set; }
        public virtual Rol Rol { get; set; }
        public virtual ICollection<Sepet> Sepet { get; set; }
    }
}
